Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/08/2020
Var
// Seção de Declarações das variáveis 
 nome : caractere
 idade : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval ("digite seu nome: ")
   leia (nome)

   escreval ("digite sua idade: ")
   leia (idade)
Fimalgoritmo