Algoritmo "Código e quantidade"
// Ler código dos produtos e mostrar quanto há disponível em estoque

Var

codigo : vetor [0..399] de inteiro
qntd_estoque : vetor [0..399] de inteiro
contador : inteiro

Inicio

 para contador de 0 ate 399 faca
    escreva ("Código do produto:")
    leia (codigo[contador])

    escreva ("Quantidade em estoque:")
    leia (qntd_estoque[contador])

 fimpara


Fimalgoritmo